### ISSUE TITLE
fetch_pairwise_genome.py producing empty pair directories

### ISSUE THREAD

**Issue by hhassle** [cvn001/RecentHGT#3]
Hi-
I am trying to work through your example data currently and I am running into an issue when using fetch_pairwise_genome.py I am executing it in my ITEP directory and it runs without giving me any error messages. It is producing a directory called all_strain_pairs which contains 49 pair directories. I believe that these 49 pair directories should contain the homologous gene clusters of each pair however they are all empty. Some guidance would be appreciated as far as what I could be missing.

Best,
Hayley Hassler

**Comment by uzunmasha** [comment]
Hello!
When I try to run fetch_pairwise_genome.py it gives an error:
Traceback (most recent call last): 
File "/home/uzun/HGT/clusterDbAnalysis/src/db_findClustersByOrganismList.py", line 10, in <module> 
from CoreGeneFunctions import * 
File "/usr/lib/python2.7/CoreGeneFunctions.py", line 16, in <module> 
from ete2 import TextFace 
ImportError: cannot import name TextFace
Can you help me with this? 
Or maybe you can just say what kind of files should be in all_strain_pairs directory (database or fasta files)?

Thanks in advance,
Maria Uzun
